### ISSUE TITLE
Possible WebPack compatibility issue?

### ISSUE THREAD

**Issue by burkeholland** [telerik/backend-services-js-sdk#4]
Hey folks

I've been using WebPack a lot lately, and I noticed that the Everlive SDK currently causes WebPack to throw a warning...

    WARNING in ./app/components/everlive/src/everlive.js
    Critical dependencies:
    1:207-214 This seem to be a pre-built javascript file. Even while this is possible, it's not recommended.
    Try to require to orginal source to get better results.
    @ ./app/components/everlive/src/everlive.js 1:207-214

And when run in the browser, Everlive is not defined. This happens without even trying to use Everlive. It looks like the error occurs when WebPack tries to require Everlive in.

I have created a [sample project](https://github.com/burkeholland/webpack-everlive) to recreate the issue with just `everlive.js`. Note that this does NOT happen with `reqwest`, `underscore`, `rsvp` or `jstimezonedetect`.

**Comment by gngeorgiev** [comment]
Hey there @burkeholland,

I investigated the issue with webpack and it seems that the best approach here is to use the `script-loader` package. This will execute the script as it would execute it in the browser which will create a global variable `Everlive` - `window.Everlive`, which is the equivalent of adding `everlive.js` with a `script` tag to your html. I have submitted a [pull request](https://github.com/burkeholland/webpack-everlive/pull/1) so you can see the changes.
