### ISSUE TITLE
Facebook Social Login (Registration) Broken with API v2.4

### ISSUE THREAD

**Issue by mobutils** [telerik/backend-services-js-sdk#5]
With Facebook enforcing their latest API version on all newly created FB applications their latest change breaks the registration process as currently implemented in Everlive. Specifically FB API V2.4 requires the use of a 'fields' URL parameter to specify which fields are returned in the response. The result of this is that the Identity object attached with the user will now only contain the ID and Name of the Facebook user and not any additional fields that relate to the requested scope.

**Comment by AntonDobrev** [comment]
The matter is discussed [here](http://www.telerik.com/forums/social-login-user-data) and mainly concerns the server integration. That is why I am closing the issue.
